# Generated by Django 4.2.3 on 2023-07-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='prio',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='prio',
            new_name='priority',
        ),
        migrations.AlterField(
            model_name='capture',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='projects',
            field=models.ManyToManyField(related_name='parent_goal', to='core.project'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='tasks',
            field=models.ManyToManyField(related_name='parent_goal', to='core.task'),
        ),
        migrations.AlterField(
            model_name='goaltree',
            name='domains',
            field=models.ManyToManyField(related_name='+', to='core.domain'),
        ),
        migrations.AlterField(
            model_name='task',
            name='needcomputer',
            field=models.BooleanField(verbose_name='does this task require a computer?'),
        ),
    ]
